// <auto-generated />
namespace DayBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix10));
        
        string IMigrationMetadata.Id
        {
            get { return "201807100917080_fix10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
